# Generated by Django 3.2.15 on 2022-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_company_companyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
