# Generated by Django 3.2.15 on 2022-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
