# Generated by Django 3.2.15 on 2022-12-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20221215_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='account.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='account.profile'),
        ),
    ]
