# Generated by Django 3.2.15 on 2022-12-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20221215_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='is_owner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
