# Generated by Django 3.2.15 on 2023-01-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.FloatField(default=0)),
                ('los', models.FloatField(default=0)),
                ('ri', models.FloatField(default=0)),
                ('lofc', models.FloatField(default=0)),
                ('sop', models.FloatField(default=0)),
                ('author_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='account.company')),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='account.profile')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='account.company')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileRate',
        ),
    ]
