# Generated by Django 3.2.15 on 2023-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20230104_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='loc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='lofc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='los',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='ri',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='sop',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lofc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='los',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ri',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sop',
            field=models.FloatField(default=0, null=True),
        ),
    ]
