# Generated by Django 3.2.15 on 2023-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20230104_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployee',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='lofc',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='los',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='ri',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='sop',
        ),
        migrations.AddField(
            model_name='company',
            name='loc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lofc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='los',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ri',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sop',
            field=models.FloatField(default=0, null=True),
        ),
    ]
