# Generated by Django 3.2.15 on 2023-01-14 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20230106_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='loc',
            field=models.FloatField(default=0, verbose_name='Level of Communication'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='lofc',
            field=models.FloatField(default=0, verbose_name='Level of Freight Care'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='los',
            field=models.FloatField(default=0, verbose_name='Level of Service'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ri',
            field=models.FloatField(default=0, verbose_name='Reliable Information'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sop',
            field=models.FloatField(default=0, verbose_name='Speed of Payment'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc', models.BooleanField(default=False, verbose_name='No Communication')),
                ('ds', models.BooleanField(default=False, verbose_name='Dissatisfied Service')),
                ('ui', models.BooleanField(default=False, verbose_name='Unreliable Information')),
                ('ff', models.BooleanField(default=False, verbose_name='Freight Failure')),
                ('np', models.BooleanField(default=False, verbose_name='No Payments')),
                ('author_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockeds', to='account.company')),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockeds', to='account.profile')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='account.company')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='account.profile')),
            ],
        ),
    ]
