# Generated by Django 3.2.15 on 2023-01-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20230114_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ds_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Dissatisfied Service'),
        ),
        migrations.AddField(
            model_name='company',
            name='ff_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Freight Failure'),
        ),
        migrations.AddField(
            model_name='company',
            name='nc_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field No Communication'),
        ),
        migrations.AddField(
            model_name='company',
            name='np_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field No Payments'),
        ),
        migrations.AddField(
            model_name='company',
            name='ui_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Unreliable Information'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ds_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Dissatisfied Service'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ff_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Freight Failure'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nc_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field No Communication'),
        ),
        migrations.AddField(
            model_name='profile',
            name='np_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field No Payments'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ui_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Blocked by field Unreliable Information'),
        ),
    ]
