# Generated by Django 5.0 on 2023-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_company_telegram_remove_profile_ds_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
