# Generated by Django 5.0 on 2023-12-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_company_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ms',
            new_name='mc',
        ),
    ]
