# Generated by Django 5.0 on 2023-12-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_ms_company_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='entity_type',
            field=models.CharField(choices=[('Carrier_dispatcher', 'carrier_dispatcher'), ('Carrier', 'carrier'), ('Broker', 'broker'), ('Shipper', 'shipper')], default='Carrier', max_length=20),
        ),
    ]
