class Load:
    origin: str
    dh_o: float
    destination: str
    dh_d: float
    distance: float
    pu_date: str
    age: int
    length: float
    weight: float
    dlv_date: str
    ref: str
    commodity: str
    price: float
    type_operator: str
    types: list[int]
    truck_status: str
    name: str
    contact_type: str
    contact: str
    description: str
