# Generated by Django 3.2.15 on 2022-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
    ]
