# Generated by Django 3.2.15 on 2022-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_load_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
