# Generated by Django 3.2.15 on 2022-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_search_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
