# Generated by Django 3.2.15 on 2022-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_load_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
