# Generated by Django 3.2.15 on 2022-08-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_search_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='wieght',
            new_name='weight',
        ),
    ]
