# Generated by Django 3.2.15 on 2022-09-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_wieght_search_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.CharField(max_length=255)),
                ('do', models.CharField(max_length=255)),
                ('value', models.FloatField(null=True)),
            ],
        ),
    ]
