# Generated by Django 3.2.15 on 2022-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='dh_d',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='dh_o',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='suggested_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='wieght',
            field=models.FloatField(null=True),
        ),
    ]
