# Generated by Django 3.2.15 on 2022-09-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220902_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='published_date',
            new_name='pickup_date',
        ),
    ]
