# Generated by Django 3.2.15 on 2022-09-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220805_2159'),
        ('main', '0009_rename_published_date_search_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='account.profile'),
        ),
    ]
