# Generated by Django 3.2.15 on 2022-09-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_load_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='wieght',
            new_name='weight',
        ),
    ]
