# Generated by Django 3.2.15 on 2022-09-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220911_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadtype',
            name='description',
        ),
    ]
