# Generated by Django 3.2.15 on 2022-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_loadtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
