# Generated by Django 3.2.15 on 2022-09-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_load_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='comment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='contact_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
