# Generated by Django 3.2.15 on 2022-09-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='do',
            new_name='load_address',
        ),
        migrations.RenameField(
            model_name='distance',
            old_name='od',
            new_name='search_address',
        ),
    ]
