# Generated by Django 3.2.15 on 2022-09-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220922_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='value',
            new_name='distance',
        ),
    ]
