# Generated by Django 3.2.15 on 2022-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_load_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
