# Generated by Django 3.2.15 on 2022-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220927_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='ref_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
