# Generated by Django 3.2.15 on 2022-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_load_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
