# Generated by Django 3.2.15 on 2022-12-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20221215_0242'),
        ('main', '0023_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='account.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
