# Generated by Django 5.0 on 2023-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20221215_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='commodity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='dlv_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='truck_status',
            field=models.CharField(blank=True, choices=[('FTL', 'FTL'), ('LTL', 'LTL'), ('BOTH', 'BOTH')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='type_operator',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('ONLY', 'ONLY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='truck_status',
            field=models.CharField(blank=True, choices=[('FTL', 'FTL'), ('LTL', 'LTL'), ('BOTH', 'BOTH')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='type_operator',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('ONLY', 'ONLY')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='load',
            name='type',
        ),
        migrations.RemoveField(
            model_name='search',
            name='type',
        ),
        migrations.AddField(
            model_name='load',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_loads', to='main.loadtype'),
        ),
        migrations.AddField(
            model_name='search',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_searches', to='main.loadtype'),
        ),
    ]
