# Generated by Django 5.0 on 2024-01-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_loadtypecategory_loadtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='main.loadtypecategory'),
        ),
    ]
